GET https://localhost:5001/server/jobs/v1/id/00000000/1
Accept: multipart/parallel
Accept-Item: application/json


###
GET https://localhost:5001/server/jobs/v1/id/00000000/2
Accept: application/msgpack

###
POST https://localhost:5001/server/jobs/v1/id/00000000/1?action=cancel

###
# @name jwt
GET https://localhost:5001/server/auth/token
Accept: application/json
Authorization: Basic admin:admin

###
GET https://localhost:5001/server/auth/token
Accept: application/jwt+json
Authorization: Basic admin:admin

###
GET https://localhost:5001/server/auth/token
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RldmUiLCJuYmYiOjE2NDU2NDcxMzksImV4cCI6MTY3NzE4MzEzOSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxLyJ9.4OfWYu7E2xGEx1P18wJUC3lz_DQNzd2Kik_dJ-jVZCA

###
DELETE https://localhost:5001/server/jobs/v1/id/00000000/52
Accept: application/json
Authorization: Bearer {{jwt.response.body.token}}

###
DELETE https://localhost:5001/server/jobs/v1/admin/id/00000000/23
Accept: application/json
Authorization: Bearer {{jwt.response.body.token}}

###
GET https://localhost:5001/server/auth/cookie
Accept: application/json
Authorization: Basic steve:steve

###
POST https://localhost:5001/server/requests/multi2
Content-Type: application/json
Authorization: Bearer {{jwt.response.body.token}}

[
  {
    "name": "Call-97.75-19.45-51m",
    "T": "2026-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1945,
    "q": 0,
    "S": 97.75,
    "K": 100,
    "c": true,
    "u": 1,
    "w": 30000
  },
  {
    "name": "Call-95.77-25.02-45m",
    "T": "2025-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2502,
    "q": 0,
    "S": 95.77,
    "K": 100,
    "c": true,
    "u": 25000
  },
  {
    "name": "Call-81.45-24.06-3m",
    "T": "2022-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2406,
    "q": 0,
    "S": 81.45,
    "K": 100,
    "c": true,
    "u": 13000
  },
  {
    "name": "Call-98.29-27.27-30m",
    "T": "2024-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2727,
    "q": 0,
    "S": 98.29,
    "K": 100,
    "c": true,
    "u": 5000
  },
  {
    "name": "Call-107.56-39.08-48m",
    "T": "2026-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3908,
    "q": 0,
    "S": 107.56,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-95.14-33.47-6m",
    "T": "2022-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3347,
    "q": 0,
    "S": 95.14,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-87.16-37.96-12m",
    "T": "2023-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3796,
    "q": 0,
    "S": 87.16,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-90.19-43.22-57m",
    "T": "2026-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4322,
    "q": 0,
    "S": 90.19,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-83.80-35.77-54m",
    "T": "2026-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3577,
    "q": 0,
    "S": 83.8,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-89.58-16.69-54m",
    "T": "2026-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1669,
    "q": 0,
    "S": 89.58,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-109.63-25.42-18m",
    "T": "2023-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2542,
    "q": 0,
    "S": 109.63,
    "K": 100,
    "c": true,
    "u": 8000
  },
  {
    "name": "Call-100.34-8.66-60m",
    "T": "2027-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.0866,
    "q": 0,
    "S": 100.34,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-87.69-54.43-21m",
    "T": "2023-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.5443,
    "q": 0,
    "S": 87.69,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-86.19-22.85-60m",
    "T": "2027-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2285,
    "q": 0,
    "S": 86.19,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-99.68-31.94-57m",
    "T": "2026-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3194,
    "q": 0,
    "S": 99.68,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-74.21-42.87-18m",
    "T": "2023-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4287,
    "q": 0,
    "S": 74.21,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-90.70-19.73-39m",
    "T": "2025-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1973,
    "q": 0,
    "S": 90.7,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-110.67-21.49-27m",
    "T": "2024-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2149,
    "q": 0,
    "S": 110.67,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-120.97-27.58-15m",
    "T": "2023-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2758,
    "q": 0,
    "S": 120.97,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-106.95-15.30-36m",
    "T": "2025-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.153,
    "q": 0,
    "S": 106.95,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-88.38-21.74-12m",
    "T": "2023-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2174,
    "q": 0,
    "S": 88.38,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-82.95-46.36-6m",
    "T": "2022-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4636,
    "q": 0,
    "S": 82.95,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-117.30-35.03-51m",
    "T": "2026-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3503,
    "q": 0,
    "S": 117.3,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-107.03-19.25-39m",
    "T": "2025-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1925,
    "q": 0,
    "S": 107.03,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-94.42-13.63-33m",
    "T": "2024-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1363,
    "q": 0,
    "S": 94.42,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-78.21-19.97-21m",
    "T": "2023-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1997,
    "q": 0,
    "S": 78.21,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-103.67-39.62-51m",
    "T": "2026-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3962,
    "q": 0,
    "S": 103.67,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-93.89-16.27-57m",
    "T": "2026-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1627,
    "q": 0,
    "S": 93.89,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-121.32-44.57-9m",
    "T": "2022-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4457,
    "q": 0,
    "S": 121.32,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-111.35-45.85-39m",
    "T": "2025-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4585,
    "q": 0,
    "S": 111.35,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-109.19-32.88-57m",
    "T": "2026-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3288,
    "q": 0,
    "S": 109.19,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-112.36-31.11-3m",
    "T": "2022-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3111,
    "q": 0,
    "S": 112.36,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-124.04-48.39-39m",
    "T": "2025-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4839,
    "q": 0,
    "S": 124.04,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-98.81-24.14-15m",
    "T": "2023-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2414,
    "q": 0,
    "S": 98.81,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-137.65-23.52-3m",
    "T": "2022-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2352,
    "q": 0,
    "S": 137.65,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-115.41-27.44-9m",
    "T": "2022-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2744,
    "q": 0,
    "S": 115.41,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-123.20-33.36-15m",
    "T": "2023-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3336,
    "q": 0,
    "S": 123.2,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-115.15-43.95-15m",
    "T": "2023-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4395,
    "q": 0,
    "S": 115.15,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-92.18-21.92-9m",
    "T": "2022-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2192,
    "q": 0,
    "S": 92.18,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-137.58-43.31-3m",
    "T": "2022-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4331,
    "q": 0,
    "S": 137.58,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-87.69-27.69-45m",
    "T": "2025-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2769,
    "q": 0,
    "S": 87.69,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-105.06-18.29-33m",
    "T": "2024-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1829,
    "q": 0,
    "S": 105.06,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-100.06-12.87-33m",
    "T": "2024-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1287,
    "q": 0,
    "S": 100.06,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-106.61-27.81-12m",
    "T": "2023-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2781,
    "q": 0,
    "S": 106.61,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-102.30-20.21-36m",
    "T": "2025-02-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2021,
    "q": 0,
    "S": 102.3,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-114.04-18.55-51m",
    "T": "2026-05-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.1855,
    "q": 0,
    "S": 114.04,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-125.31-22.74-33m",
    "T": "2024-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.2274,
    "q": 0,
    "S": 125.31,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-89.30-48.65-21m",
    "T": "2023-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4865,
    "q": 0,
    "S": 89.3,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-107.65-38.83-42m",
    "T": "2025-08-08T00:00:00-04:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.3883,
    "q": 0,
    "S": 107.65,
    "K": 100,
    "c": true,
    "u": 1
  },
  {
    "name": "Call-134.18-47.21-21m",
    "T": "2023-11-08T00:00:00-05:00",
    "t": "2022-02-08T00:00:00-05:00",
    "r": 0,
    "sigma": 0.4721,
    "q": 0,
    "S": 134.18,
    "K": 100,
    "c": true,
    "u": 1
  }
]
